x-shared-env: &shared-api-env
  APP_PORT: ${APP_PORT:-4000}
  DB_HOST: ${DB_HOST:-database}
  DB_PORT: ${DB_PORT:-5432}
  DB_USER: ${DB_USER:-postgres}
  DB_NAME: ${DB_NAME:-postgres}
  DB_PASSWORD: ${DB_PASSWORD:-postgres}
  DB_SSL_MODE: ${DB_SSL_MODE:-disable}
  SECRET_KEY: ${SECRET_KEY:-123456ABCDEFGH7890}

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      <<: *shared-api-env
      PGUSER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     <<: *shared-api-env
  #   ports:
  #     - ${API_PORT:-4000}:${API_PORT:-4000}
  #   depends_on:
  #     - database



